[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_BASE_URL = "/api/dify-proxy"
  API_AUTHORIZATION_TOKEN = "app-EVYktrhqnqncQSV9BdDv6uuu"
  NEXT_PUBLIC_SITE_NAME = "SEO Blog Agent"
  NEXT_PUBLIC_SITE_DESCRIPTION = "AI-powered SEO blog generation system"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
