#!/bin/bash
# 文件名：manual-deployment-guide.sh
# 用途：手动部署指南

echo "📋 ===== 手动部署指南 ====="
echo "📅 时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo "🎯 目标服务器: 10.61.153.191"
echo ""

echo "⚠️  无法直接连接到服务器，请按照以下步骤手动部署："
echo ""

echo "🔧 方法1: 使用 VPN 连接"
echo "   1. 连接到公司内网 VPN"
echo "   2. 确保可以访问 10.61.153.191"
echo "   3. 重新运行部署脚本"
echo ""

echo "🔧 方法2: 通过跳板机连接"
echo "   1. 先连接到跳板机"
echo "   2. 从跳板机连接到目标服务器"
echo "   3. 上传文件并部署"
echo ""

echo "🔧 方法3: 手动文件传输"
echo "   1. 将 deploy-package 目录打包"
echo "   2. 通过其他方式传输到服务器"
echo "   3. 在服务器上解压并部署"
echo ""

echo "📦 创建部署包压缩文件..."
tar -czf dify-proxy-deployment.tar.gz deploy-package/
echo "✅ 部署包已创建: dify-proxy-deployment.tar.gz"
echo ""

echo "📋 部署包内容:"
echo "   📁 proxy-server.js - Express 代理服务器"
echo "   📁 package.json - Node.js 依赖配置"
echo "   📁 ecosystem.config.js - PM2 进程管理配置"
echo "   📁 deploy.sh - 部署启动脚本"
echo "   📁 .env - 环境变量配置"
echo "   📁 README.md - 部署说明文档"
echo ""

echo "🚀 手动部署步骤:"
echo ""
echo "1️⃣ 上传文件到服务器"
echo "   方法A: 使用 SCP (需要 VPN)"
echo "   scp dify-proxy-deployment.tar.gz admin@10.61.153.191:/opt/"
echo ""
echo "   方法B: 使用 SFTP"
echo "   sftp admin@10.61.153.191"
echo "   put dify-proxy-deployment.tar.gz /opt/"
echo ""
echo "   方法C: 使用 rsync"
echo "   rsync -avz dify-proxy-deployment.tar.gz admin@10.61.153.191:/opt/"
echo ""

echo "2️⃣ SSH 连接到服务器"
echo "   ssh admin@10.61.153.191"
echo "   # 密码: Joyme0411!"
echo ""

echo "3️⃣ 解压并部署"
echo "   cd /opt"
echo "   tar -xzf dify-proxy-deployment.tar.gz"
echo "   mv deploy-package dify-proxy"
echo "   cd dify-proxy"
echo "   chmod +x deploy.sh"
echo "   ./deploy.sh"
echo ""

echo "4️⃣ 验证部署"
echo "   curl http://localhost:3001/health"
echo "   # 预期响应: {\"status\":\"ok\",\"timestamp\":\"...\",\"dify_api\":\"http://47.90.156.219/v1\"}"
echo ""

echo "5️⃣ 配置防火墙 (如果需要)"
echo "   sudo ufw allow 3001"
echo "   # 或者"
echo "   sudo iptables -A INPUT -p tcp --dport 3001 -j ACCEPT"
echo ""

echo "📊 服务管理命令:"
echo "   # 查看服务状态"
echo "   pm2 status"
echo ""
echo "   # 查看日志"
echo "   pm2 logs dify-proxy"
echo ""
echo "   # 重启服务"
echo "   pm2 restart dify-proxy"
echo ""
echo "   # 停止服务"
echo "   pm2 stop dify-proxy"
echo ""

echo "🔧 故障排除:"
echo "   1. 检查端口占用: netstat -tlnp | grep 3001"
echo "   2. 检查 Node.js: node --version"
echo "   3. 检查 PM2: pm2 --version"
echo "   4. 查看日志: tail -f /opt/dify-proxy/logs/combined.log"
echo ""

echo "📞 如果需要帮助:"
echo "   1. 检查服务器网络连接"
echo "   2. 确认 VPN 连接状态"
echo "   3. 验证服务器 SSH 配置"
echo "   4. 检查防火墙设置"
echo ""

echo "🎯 部署完成后:"
echo "   代理地址: http://10.61.153.191:3001"
echo "   健康检查: http://10.61.153.191:3001/health"
echo "   API 代理: http://10.61.153.191:3001/api/dify-proxy"
echo ""

echo "✅ 前端配置已更新，部署完成后即可使用新的代理服务器！"

